updated pipeline to enforce PR linking to an existing issue
Signed-off-by: Zeeshan Abid <zeeshan.abid.com@gmail.com>

diff --git a/.github/workflows/enforce-branch-name.yml b/.github/workflows/enforce-branch-name.yml
--- a/.github/workflows/enforce-branch-name.yml
+++ b/.github/workflows/enforce-branch-name.yml
@@ -27,9 +27,9 @@ jobs:
             https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }} | jq -r .body)
 
           # Regex to check if the PR description contains "Closes #<number>" or "Fixes #<number>"
-          if [[ ! "$PR_BODY" =~ (Closes\ #[0-9]+|Fixes\ #[0-9]+|Resolves\ #[0-9]+) ]]; then
-            echo "❌ Error: PR description must mention the issue number (e.g., 'Closes #123')"
-            #exit 1
+          if [[ ! "$PR_BODY" =~ ([cC]loses|[fF]ixes|[rR]esolves) \[(\#[0-9]+)\]\(.*?\) ]]; then
+            echo "❌ Error: PR description must mention the issue number (e.g., 'Closes [#123](https://github.com/org/repo/issues/123)')"
+            exit 1
           else
             echo "✅ PR description contains an issue number."
           fi
